<?php
/**
 * MerchantOfRecord
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rapid
 *
 * EPS Rapid V3
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MerchantOfRecord Class Doc Comment
 *
 * @category Class
 * @description * &#x60;expedia&#x60; - Payment is taken by Expedia. * &#x60;property&#x60; - Payment is taken by the property.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MerchantOfRecord
{
    /**
     * Possible values of this enum
     */
    public const EXPEDIA = 'expedia';

    public const PROPERTY = 'property';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXPEDIA,
            self::PROPERTY
        ];
    }
}


