<?php
/**
 * TravelCompanion
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rapid
 *
 * EPS Rapid V3
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * TravelCompanion Class Doc Comment
 *
 * @category Class
 * @description The companion category for any travelers that accompanied this reviewer.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TravelCompanion
{
    /**
     * Possible values of this enum
     */
    public const FAMILY = 'family';

    public const FAMILY_WITH_CHILDREN = 'family_with_children';

    public const PARTNER = 'partner';

    public const SELF = 'self';

    public const FRIENDS = 'friends';

    public const PET = 'pet';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FAMILY,
            self::FAMILY_WITH_CHILDREN,
            self::PARTNER,
            self::SELF,
            self::FRIENDS,
            self::PET
        ];
    }
}


